apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: aksdemo
  name: aksdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: aksdemo
  template:
    metadata:
      labels:
        k8s-app: aksdemo
    spec:
      containers:
      - name: aksdemo
        image: prafulltest/aksdemo:#{Build.BuildId}#
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: aksdemo
  name: dockerdemo-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
     k8s-app: aksdemo
  app: aksdemo